### ISSUE TITLE
Cursor is not centered properly

### ISSUE THREAD

**Issue by pyj-pd** [mechtifs/wiggle#10]
Hello, I am trying to use Wiggle with custom mouse theme—[BigSur Cursor](https://github.com/ful1e5/apple_cursor).

However, scale origin of scaled mouse cursor does not match with one of system mouse cursor, causing it to animate weirdly when reverting back to normal size.

Below is my GNOME Tweaks configuration:
![image](https://github.com/mechtifs/wiggle/assets/123401626/dc98b867-39f0-4db6-980b-4ccf47fa471c)

And here is extension configuration:
![image](https://github.com/mechtifs/wiggle/assets/123401626/6dc79433-d912-4e98-b929-872a7ff1bf1d)
![image](https://github.com/mechtifs/wiggle/assets/123401626/512f2f1c-d76f-4948-8bfc-0c4462594558)

```
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
```

**Comment by mechtifs** [comment]
it looks like you're using an older version of GNOME. the latest release has already added the feature to set custom sprite of the cursor.

also, the default one is from Adwaita (as for the reason, see #1) so it just won't look right if you're using a custom cursor theme.
you can try manually replacing `$HOME/.local/share/gnome-shell/extensions/wiggle@mechtifs/icons/cursor.svg` with the one from your cursor theme as a temporary solution.

**Comment by pyj-pd** [comment]
The cursor option appeared after updating Ubuntu.

Thank you for the help! Have a great day.
