### ISSUE TITLE
this._sprite is null

### ISSUE THREAD

**Issue by mbetrifork** [mechtifs/wiggle#12]
On my machine this extension very often, if not nearly always, fails to load with this strange error message appearing in the Extensions system app, where the extension is also disabled.

Here's some info on my system to help debug:

```bash
$ inxi -Fzxm
System:
  Kernel: 6.5.0-35-generic arch: x86_64 bits: 64 compiler: N/A Desktop: GNOME
    v: 45.2 Distro: Ubuntu 23.10 (Mantic Minotaur)
Machine:
  Type: Laptop System: Dell product: Latitude 5511 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 0GYJNK v: A00 serial: <superuser required> UEFI: Dell
    v: 1.27.0 date: 01/29/2024

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic

$ uname -a
Linux my-ubuntu 6.5.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Fri Apr 26 11:23:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mechtifs** [comment]
It seems like you're using an older version of GNOME, which I'm not planned to support anymore since it could be too much work to test & fix. If the same issue occurs when you updated to the latest version, feel free to let me know :)
