### ISSUE TITLE
System does not register clicks after "wiggle"

### ISSUE THREAD

**Issue by Beast-Viper** [mechtifs/wiggle#13]
When I shake the cursor it gets enlarged by the extension but after it returns back to its original state I am unable to click on anything as it does not get registered. 

Temporary solution is to lock screen and unlock.

Here is my system specs:
![Screenshot from 2024-07-07 16-35-22](https://github.com/mechtifs/wiggle/assets/95138842/fb68d89b-7f09-4d3e-bf75-df08f4ae2995)

Tell me if I need to send logs.

**Comment by mechtifs** [comment]
Did you install the extension from E.G.O? Please try the latest commit :)

**Comment by Beast-Viper** [comment]
Yes I have installed it from the extensions website. Do I need to install from github?

Sent from Proton Mail Android

-------- Original Message --------

**Comment by mechtifs** [comment]
Yes please. The latest changes will always be on GitHub since I'm not aware of which version breaks the E.G.O one :)

**Comment by Beast-Viper** [comment]
Ok I will inform after I get to my computer.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Beast-Viper** [comment]
How do I build the github version?

Sent from Proton Mail Android

-------- Original Message --------

**Comment by mechtifs** [comment]
Download source code as zip then run `gnome-extensions install wiggle-master.zip`.

**Comment by Beast-Viper** [comment]
Working correctly now.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Beast-Viper** [comment]
Fixed now
