### ISSUE TITLE
Suggestion: Disable on apps which hide the cursor

### ISSUE THREAD

**Issue by EPOCHvoyager** [mechtifs/wiggle#7]
Especially relevant on applications like games, where you might regularly need to move the cursor in an equivalent motion to wiggling it around. Perhaps making a distinction as to whether the app is fullscreen or not would be useful as well.

**Comment by Lija321** [comment]
But like using a fullscreen web browser is pretty common, maybe like have a whitelist of apps over which it shouldnt appear

**Comment by mechtifs** [comment]
i've added an additional check to determine whether wiggle should be paused under certain circumstances. could you help try it out and see if it's working properly?

**Comment by EPOCHvoyager** [comment]
Having a little trouble trying out the changes, as I'm currently running GNOME 45. Tried cherry-picking from d7f679aacb28b099a641311d0f0f623df39f1cbe, but the merge conflicts due to a88260162473f103733fb8a6af7a86fc6b64872a are a little confusing to someone completely unfamiliar with extension work.

**Comment by mechtifs** [comment]
by manually reverting `add_child` and `remove_child` back to `add_actor` and `remove_actor` in `effect.js` _should_ just work for GNOME 45. idk if other stuff will also break tho.

**Comment by EPOCHvoyager** [comment]
No dice on my end; while it now loads fine with those modifications, the scaling behavior is completely non-functional.

**Comment by mechtifs** [comment]
that's unfortunate. i have no idea what could go wrong :(
the journal may contain some useful information. maybe take a look?

**Comment by EPOCHvoyager** [comment]
Apologize for the late report, but I am now able to test this feature after moving to Bazzite(GNOME 46) a couple of days ago. While it thankfully does work well in applications which hide the cursor completely, games that seem to make use of the hardware cursor directly, but replace it with another image seem to not be affected. Is this intended behavior?

A rundown of the applications I've tested - Terraria works well(seems to be a software cursor), Dota 2 displays the enlarged Adwaita cursor, same is true of Magic The Gathering: Arena and Ori and the Blind Forest: Definitive Edition(the latter two, running on Proton).

**Comment by mechtifs** [comment]
> While it thankfully does work well in applications which hide the cursor completely, games that seem to make use of the hardware cursor directly, but replace it with another image seem to not be affected.

You're right. Unfortunately I was not able to test out all scenarios in my daily use :(

It certainly could be fixed, however there is currently a bug which prevents extensions from getting the cursor bitmap. Please check #11 for more information :)
